version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood-store-api
    ports:
      - "3000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=172.104.170.224;Database=nad_1;Username=nad;Password=anhdung2004;
    restart: always

volumes:
  postgres_data:

networks:
  fastfood-network:
    driver: bridge