version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood-store-api
    ports:
      - "3000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=nad_1;Username=nad;Password=anhdung2004;
    restart: always
    depends_on:
      - postgres
    networks:
      - fastfood-network

  postgres:
    image: postgres:16
    container_name: fastfood-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nad
      - POSTGRES_PASSWORD=anhdung2004
      - POSTGRES_DB=nad_1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - fastfood-network

volumes:
  postgres_data:

networks:
  fastfood-network:
    driver: bridge