name: Deploy to Akamai Cloud

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /app/FastFoodStore
            git fetch origin master
            git reset --hard origin/master
            docker compose down
            docker compose up -d --build
            echo "Deploy thanh cong!"